name: Auto-Report Issue
description: Report an issue for automatic triage and potential fix
title: "[Auto-Report]: "
labels: ["auto-report"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! This template is for issues that should be automatically triaged and potentially fixed by AI.

        The auto-triage workflow will:
        1. Analyze your issue using Claude AI
        2. Categorize it (api-error, outdated-docs, pitfall, other)
        3. Assign a confidence score
        4. If confidence is high (≥80%), automatically propose a fix via PR

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - API Error - Wrong endpoint, authentication, or API call
        - Outdated Documentation - Docs reference deprecated features
        - Missing Pitfall - Common mistake not documented
        - Other - Something else
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear description of the issue
      placeholder: |
        What went wrong? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error Message (if applicable)
      description: Copy and paste any error messages or unexpected output
      render: shell
      placeholder: |
        Paste error messages here...

  - type: textarea
    id: affected-files
    attributes:
      label: Affected Files
      description: Which documentation files or sections are affected?
      placeholder: |
        - plugins/component-developer/SKILL.md (line 123)
        - plugins/dataapp-developer/guides/best-practices.md

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Open plugins/component-developer/SKILL.md
        2. Try the code example in the "Authentication" section
        3. Error occurs: ...

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: |
        The code example should work without errors...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - This started happening after the API update in December 2025
        - Similar issue: #123
        - Related documentation: https://developers.keboola.com/...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have provided a clear description
          required: true
        - label: I have included relevant file paths (if applicable)
          required: false
